In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
mogumogu_potato = pd.read_csv('mogumogu_potato.csv')
mogumogu_potato

    ポテトの長さ
0      4.5
1      4.2
2      3.9
3      6.6
4      0.8
5      5.6
6      3.2
7      6.9
8      4.4
9      4.7
10     3.8
11     3.0
12     3.2
13     4.9
14     7.6
15     3.3
16     7.0
17     3.7
18     3.0
19     4.1
20     5.8
21     4.6
22     4.0
23     2.2
24     7.7
25     3.9
26     6.7
27     3.3
28     7.5
29     2.7
30     5.4
31     5.8
32     5.9
33     3.2
34     5.1
35     3.1
36     6.1
37     4.6
38     2.2
39     4.0
40     6.4
41     5.2
42     3.3
43     6.4
44     6.4
45     2.6
46     2.6
47     5.2
48     5.8

In [3]:
mogumogu_potato.mean()

ポテトの長さ    4.614286
dtype: float64

In [4]:
wakuwaku_potato = pd.read_csv('wakuwaku_potato.csv')
wakuwaku_potato

    ポテトの長さ
0      3.5
1      3.8
2      5.8
3      6.4
4      4.2
5      4.2
6      4.0
7      3.6
8      3.8
9      5.2
10     4.9
11     5.2
12     6.0
13     3.9
14     5.3
15     4.6
16     3.9
17     4.2
18     4.2
19     6.4
20     2.8
21     5.6
22     5.7
23     5.1
24     4.4
25     5.6
26     5.3
27     3.9
28     5.1
29     3.6
30     4.2
31     5.0
32     4.7
33     4.1
34     3.7
35     4.9
36     4.7
37     5.3
38     3.6
39     4.2
40     4.4
41     4.0
42     5.5
43     4.2
44     4.8
45     3.7
46     3.1
47     4.7
48     5.0

In [5]:
wakuwaku_potato.mean()

ポテトの長さ    4.571429
dtype: float64

In [107]:
# もぐもぐバーガーのポテトの度数分布
column_name = mogumogu_potato.columns[0]
new_columns_name = ('0cm以上1cm未満', '2cm以上3cm未満', '3cm以上4cm未満', '4cm以上5cm未満', '5cm以上6cm未満', '6cm以上7cm未満', '7cm以上8cm未満')
length_0_1 = mogumogu_potato[mogumogu_potato[column_name] < 1].rename(columns={column_name: new_columns_name[0]})[new_columns_name[0]]
length_2_3 = mogumogu_potato[(2 <= mogumogu_potato[column_name]) & (mogumogu_potato[column_name] < 3)].rename(columns={column_name: new_columns_name[1]})[new_columns_name[1]]
length_3_4 = mogumogu_potato[(3 <= mogumogu_potato[column_name]) & (mogumogu_potato[column_name] < 4)].rename(columns={column_name: new_columns_name[2]})[new_columns_name[2]]
length_4_5 = mogumogu_potato[(4 <= mogumogu_potato[column_name]) & (mogumogu_potato[column_name] < 5)].rename(columns={column_name: new_columns_name[3]})[new_columns_name[3]]
length_5_6 = mogumogu_potato[(5 <= mogumogu_potato[column_name]) & (mogumogu_potato[column_name] < 6)].rename(columns={column_name: new_columns_name[4]})[new_columns_name[4]]
length_6_7 = mogumogu_potato[(6 <= mogumogu_potato[column_name]) & (mogumogu_potato[column_name] < 7)].rename(columns={column_name: new_columns_name[5]})[new_columns_name[5]]
length_7_8 = mogumogu_potato[(7 <= mogumogu_potato[column_name]) & (mogumogu_potato[column_name] < 8)].rename(columns={column_name: new_columns_name[6]})[new_columns_name[6]]
mogumogu_fd = pd.DataFrame(length_0_1)
mogumogu_fd = mogumogu_fd.join(length_1_2)
mogumogu_fd = mogumogu_fd.join(length_2_3)
mogumogu_fd = mogumogu_fd.join(length_3_4)
mogumogu_fd = mogumogu_fd.join(length_4_5)
mogumogu_fd = mogumogu_fd.join(length_5_6)
mogumogu_fd = mogumogu_fd.join(length_6_7)
mogumogu_fd = mogumogu_fd.join(length_7_8)
mogumogu_fd = mogumogu_fd.fillna(0)
mogumogu_fd